[package]
name = "kur"
version = "0.1.9"
edition = "2021"
description = "One Package Manager To Rule Them All"
license = "MIT"
documentation = "https://github.com/dammerung2718/kur"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
os_type = "2.6.0"
